# Generated by Django 3.1.1 on 2021-02-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='facebook',
            field=models.CharField(default='some_value', max_length=300, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='instagram',
            field=models.CharField(default='some_value', max_length=300, verbose_name='Instagram'),
        ),
    ]
