# Generated by Django 3.1.6 on 2021-02-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='facebook',
            field=models.CharField(max_length=400, null=True, verbose_name='Perfil Facebook *'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='instagram',
            field=models.CharField(max_length=400, null=True, verbose_name='Perfil Instagram *'),
        ),
    ]
