# Generated by Django 3.1.6 on 2021-02-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='avatar',
            field=models.ImageField(blank=True, default='media/media/avatar.jpg', null=True, upload_to='media/'),
        ),
    ]
