# Generated by Django 3.1.1 on 2021-02-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20210204_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='facebook',
            field=models.CharField(blank=True, default='some_value', max_length=300, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='instagram',
            field=models.CharField(blank=True, default='some_value', max_length=300, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_cri',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Registro CRI *'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone'),
        ),
    ]
