# Generated by Django 3.1.1 on 2021-02-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='valor',
            field=models.DecimalField(decimal_places=2, default='some_value', max_digits=8),
        ),
    ]
