# Generated by Django 3.1.1 on 2021-02-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0002_auto_20210204_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='video',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
