# Generated by Django 3.1.1 on 2021-02-04 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imovel', '0003_imovel_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='categoria',
            field=models.TextField(blank=True, choices=[('Alto Padrão', 'Alto Padrão'), ('Médio Padrão', 'Médio Padrão'), ('Baixo Padrão', 'Baixo Padrão')], null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='corretor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='descricao',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='endereco',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='localizacao',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='negocio',
            field=models.TextField(blank=True, choices=[('Aluguel', 'Aluguel'), ('Arrendamento', 'Arrendamento'), ('Em Construção', 'Em Construção'), ('Venda', 'Venda')], null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='propriedade',
            field=models.TextField(blank=True, choices=[('Apartamento', 'Apartamento'), ('Casa', 'Casa'), ('Casa Condomínio', 'Casa Condomínio'), ('Casa Vila', 'Casa Vila'), ('Cobertura', 'Cobertura'), ('Comercial', 'Comercial'), ('Fazenda', 'Fazenda'), ('Flat', 'Flat'), ('Kitnet', 'Kitnet'), ('Loft', 'Loft'), ('Sobrado', 'Sobrado'), ('Terreno', 'Terreno Padrão')], null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default='some_value', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='video',
            field=models.CharField(blank=True, default='some_value', max_length=3000, null=True),
        ),
    ]
