# Generated by Django 3.1.6 on 2021-02-18 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(blank=True, max_length=100, null=True, verbose_name='endereço')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='bairro')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.pessoa')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=11, null=True, verbose_name='RG')),
            ],
            options={
                'verbose_name': 'pessoa física',
                'verbose_name_plural': 'pessoas físicas',
                'ordering': ('nome',),
            },
            bases=('crm.pessoa',),
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.pessoa')),
                ('razao_social', models.CharField(max_length=100, verbose_name='razão social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=100, null=True, verbose_name='nome fantasia')),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=25, null=True, verbose_name='inscrição estadual')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=25, null=True, verbose_name='inscrição municipal')),
            ],
            options={
                'verbose_name': 'pessoa jurídica',
                'verbose_name_plural': 'pessoas jurídicas',
                'ordering': ('razao_social',),
            },
            bases=('crm.pessoa',),
        ),
    ]
